name: Snapcast Client (Automatic)
version: "0.1.20"
slug: snapcast_client_automatic
description: Automatically create Snapcast clients for each soundcard of your HASS server
url: https://github.com/8999400/homeassistant-addons-snapcast/tree/main/snapclient
startup: services
boot: auto
init: false
audio: true
options:
  url: tcp://snapcastserver
  filters: []
schema:
  url: str
  filters:
    - conditions:
        - str?
      accept: bool?
      latency: int?
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
